name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install
        working-directory: ./comments

      - name: Typecheck
        run: pnpm run typecheck
        working-directory: ./comments

      - name: Lint
        run: pnpm run lint
        working-directory: ./comments

      - name: Print Environment Variable
        run: echo $MY_ENV_VAR
        working-directory: ./comments

      - name: Unit Tests
        run: pnpm run test
        working-directory: ./comments